### ISSUE TITLE
Research: can we leverage "Pre" PR web hooks

### ISSUE THREAD

**Issue by wreyniers** [bythepixel/git-webhooks#19]
In #17 - PR Title grooming we're having to rename PR's if they are named improperly. To avoid history clutter on the PR, we'd like to see if there's a way we can do PR name automatically or at least validated prior to submission. 

- [ ] Determine if we can use Pre PR creation web hooks to improve #17

**Comment by HeathNaylor** [comment]
Does not look to be possible with pull requests.

The action that was performed. Can be one of "assigned", "unassigned", "labeled", "unlabeled", "opened", "edited", "closed", or "reopened".
